import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import {Navbar} from '../components/Navbar';
import { useState } from 'react';
import { Images } from '../components/Images';
import { motion } from 'framer-motion';
import useFirestore from '../hooks/useFirestore'
import ProgressBar from '../components/ProgressBar';


export default function Home() {
  const[file,setFile]=useState("");
  const {docs}=useFirestore('images');
  const[error,setError]=useState('');


  const types=['image/png','image/jpeg'];

  const handleChange=e=>{
    let selected=e.target.files[0]
    if(selected && types.includes(selected.type)){
      setFile(selected);
      setError(null)
    }else{
      setFile(null)
      setError('Please select image file, only support png/jpeg formats')
    }
  };


  return (
    <>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Navbar/>
      </header>

      <main className={styles.main}>
        <div className={styles.uploadContainer}>
          <div className={styles.wrapper}>
            <div className={styles.input}>
              <input onChange={handleChange} id='upload' type="file" />
              <label htmlFor="upload">
              <Image style={{cursor:'pointer'}} width={100} height={100} src='/uploadIcon.svg'/>
              </label>
              {file&&  <p className={styles.fileName}>{file.name}</p>}
              {file && <ProgressBar file={file} setFile={setFile}/>}
            </div>
              {error &&<p style={{
                color:'red',
                fontSize:'1.3em'
              }}>{error}</p>}
          </div>
          <div className={styles.imageContainer}>
            {docs.map(doc=>   <motion.div    initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1 }} key={doc.id} className={styles.images}>
          <Images url={doc.url} id={doc.id} />

            </motion.div>)}
         
          </div>
         
        </div>
      </main>

     
      </>
  )
}
